### ISSUE TITLE
how to set up a remote server

### ISSUE THREAD

**Issue by marcinjurek** [uqfoundation/ppft#16]
Hello, I'm trying to use the ParallelPool class and I followed everything in https://github.com/uqfoundation/ppft/issues/15#issuecomment-406069659
However, it still doesn't work for me, i.e. the script running on the client never exits but also doesn't print any error message. Here is a screen shot showing the remote server on the left (and the command I ran), and the top listing of running processes. On the right hand side is the script I ran. I'm really clueless how to debug it further. Thanks for any suggestions!
![scrren](https://user-images.githubusercontent.com/6467709/44289889-cd8adc80-a23b-11e8-95ae-252f1f6a0f23.png)

**Comment by mmckerns** [comment]
Hmm... this has puzzled me.  If you are doing exactly what is in the comment on #15, but it still doesn't work and you don't get any error --- just a hang.... I'm not sure why.  Did you try setting the `logging` level to something more verbose (i.e. with the `-d` option on the server)?

**Comment by mmckerns** [comment]
This issue is stale, and should be resolved by https://github.com/uqfoundation/pathos/issues/189. Closing.
