### ISSUE TITLE
can I use ppft to speed a nested loop on huge list, like:

### ISSUE THREAD

**Issue by loveJasmine** [uqfoundation/ppft#19]
for i in range(N):
for j in range(N):
calc(N[i], N[j])

N is huge, like tens of millions

**Comment by mmckerns** [comment]
yes.

The easiest interface for `ppft` is found within `pathos`.
```
>>> import pathos
>>> p = pathos.pools.ParallelPool()
>>> x = list(zip(range(4),range(-4,0)))
>>> p.map(sum, x)
[-4, -2, 0, 2]

```
`pathos` provides a `multiprocessing`-style interface for `ppft` with the `ParallelPool`.
If you want to communicate process to process at a finer granularity than a pool of workers, then use `ppft` directly.

**Comment by loveJasmine** [comment]
it works, thanks
