### ISSUE TITLE
Tag 1.6.7.8 appeared before latest tag 1.6.6.4

### ISSUE THREAD

**Issue by MicroJoe** [uqfoundation/ppft#29]
Dear maintainer,

When watching for latest version on the tags page: https://github.com/uqfoundation/ppft/tags
Latest version detected is `1.6.7.8` by semantic order, but latest released tag is `1.6.6.4`.

Please consider one of the two following options:

1. Remove the `1.6.7.8` tag; *or*
2. Release a newer tag that has a bigger semantic order than `1.6.7.8`.

Thanks.

**Comment by mmckerns** [comment]
Hi, thanks for noticing.  Releases are semantically ordered.  If you click on the link for the tag, you can see there was a typo when creating the tag.  The tag was meant to be `ppft-1.6.4.8`.
https://github.com/uqfoundation/ppft/releases/tag/ppft-1.6.7.8
The repo tag is the only place this typo propagated to, and elsewhere the release is referred to as `ppft-1.6.4.8`, as expected.

**Comment by MicroJoe** [comment]
Hello,

The issue is automatic scrapping tools like Debian's uscan is picking version `1.6.7.8` as latest version. I am packaging `ppft` to Debian, and this tag makes notifications to me that a new version is available each time. I think the best solution for Debian but also Fedora and other distribution packagers is to release a new tag that will hide this wrong tag, or delete the wrong tag.

Bests.

**Comment by mmckerns** [comment]
I'm not sure if the tag can be deleted.  I think the assets can be deleted.  Possibly a reasonable solution is a jump in the new version number.

**Comment by MicroJoe** [comment]
Hi, I agree that bumping would be the best. Bump to a version higher than `1.6.7.8` and this should fix the issue. :)

**Comment by mmckerns** [comment]
As an aside is it possible for you point at pypi instead of GitHub?  Then you should get the latest release.

**Comment by MicroJoe** [comment]
Hi, we are pointing to Github instead of PyPI because PyPI often does not contains all of the source files in the sdist. Almost all new Debian Python packages are using upstream repositories instead of PyPI to get the sources, so I am afraid this is not an option.
