### ISSUE TITLE
Bump new release version above 1.6.7.8

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/ppft#30]
A typo in the release tag for `1.6.4.8` resulted in a tag of `ppft-1.6.7.8` (see #29).  To ensure the proper latest release is automatically found, the next release version should be bumped above `1.6.7.8`.

**Comment by MicroJoe** [comment]
Hi, can we consider an empty release to bump the version number? In order to make the automatic tools happy with a proper version. Thanks in advance!

**Comment by mmckerns** [comment]
A release is planned, and should happen within the next few days.

**Comment by mmckerns** [comment]
fixed: e0c08b155e727cccf6f31cc4c0709c4525c96743
